# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aurisia.v1 import aurisia_pb2 as aurisia_dot_v1_dot_aurisia__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aurisia/v1/aurisia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioCaptureStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.unary_stream(
                '/aurisia.v1.AudioCapture/StreamAudio',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.StreamRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/aurisia.v1.AudioCapture/ListDevices',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.ListAudioDevicesRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.AudioDeviceList.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.AudioCapture/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class AudioCaptureServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioCaptureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.StreamRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.ListAudioDevicesRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.AudioDeviceList.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.AudioCapture', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.AudioCapture', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioCapture:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aurisia.v1.AudioCapture/StreamAudio',
            aurisia_dot_v1_dot_aurisia__pb2.StreamRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.AudioCapture/ListDevices',
            aurisia_dot_v1_dot_aurisia__pb2.ListAudioDevicesRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.AudioDeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.AudioCapture/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VoiceActivityDetectionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.stream_stream(
                '/aurisia.v1.VoiceActivityDetection/Detect',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.VoiceActivity.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.VoiceActivityDetection/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class VoiceActivityDetectionServicer:
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceActivityDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.stream_stream_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.VoiceActivity.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.VoiceActivityDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.VoiceActivityDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceActivityDetection:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aurisia.v1.VoiceActivityDetection/Detect',
            aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.VoiceActivity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.VoiceActivityDetection/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeechRecognitionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.stream_stream(
                '/aurisia.v1.SpeechRecognition/Recognize',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.SpeechInput.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.TranscriptEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.SpeechRecognition/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class SpeechRecognitionServicer:
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.SpeechInput.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.TranscriptEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.SpeechRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.SpeechRecognition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechRecognition:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aurisia.v1.SpeechRecognition/Recognize',
            aurisia_dot_v1_dot_aurisia__pb2.SpeechInput.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.TranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.SpeechRecognition/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SoundDetectionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.stream_stream(
                '/aurisia.v1.SoundDetection/Detect',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.SoundEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.SoundDetection/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class SoundDetectionServicer:
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoundDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.stream_stream_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.SoundEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.SoundDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.SoundDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SoundDetection:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aurisia.v1.SoundDetection/Detect',
            aurisia_dot_v1_dot_aurisia__pb2.AudioFrame.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.SoundEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.SoundDetection/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LocalizationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Estimate = channel.stream_stream(
                '/aurisia.v1.Localization/Estimate',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.LocalizationInput.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.DirectionEstimate.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.Localization/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class LocalizationServicer:
    """Missing associated documentation comment in .proto file."""

    def Estimate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Estimate': grpc.stream_stream_rpc_method_handler(
                    servicer.Estimate,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.LocalizationInput.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.DirectionEstimate.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.Localization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.Localization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Localization:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Estimate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aurisia.v1.Localization/Estimate',
            aurisia_dot_v1_dot_aurisia__pb2.LocalizationInput.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.DirectionEstimate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.Localization/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PerceptionFusionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fuse = channel.stream_stream(
                '/aurisia.v1.PerceptionFusion/Fuse',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.PerceptionInput.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.PerceptionEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aurisia.v1.PerceptionFusion/Health',
                request_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
                response_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
                _registered_method=True)


class PerceptionFusionServicer:
    """Missing associated documentation comment in .proto file."""

    def Fuse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionFusionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fuse': grpc.stream_stream_rpc_method_handler(
                    servicer.Fuse,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.PerceptionInput.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.PerceptionEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.FromString,
                    response_serializer=aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aurisia.v1.PerceptionFusion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aurisia.v1.PerceptionFusion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerceptionFusion:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fuse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aurisia.v1.PerceptionFusion/Fuse',
            aurisia_dot_v1_dot_aurisia__pb2.PerceptionInput.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.PerceptionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aurisia.v1.PerceptionFusion/Health',
            aurisia_dot_v1_dot_aurisia__pb2.HealthRequest.SerializeToString,
            aurisia_dot_v1_dot_aurisia__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
